### ISSUE TITLE
script gcode library

### ISSUE THREAD

**Issue by Xeo-Skr** [wrobell/pxf-230#1]
Hello, I have been trying to find the library you use in `scripts/nema-support`, named `dcad` but without any success.

Do you remember anything about it that could help me identifying it & find a copy of the source code ?

Thank you :)

**Comment by wrobell** [comment]
Please see https://bitbucket.org/wrobell/dcmod-cad/src/master/

**Comment by Xeo-Skr** [comment]
thank you very much :)
